### ISSUE TITLE
Add missing documentation for `requiredUnlessData` validator

### ISSUE THREAD

**Issue by bardzusny** [jbandura/ember-legit-forms-docs#5]
See https://github.com/jbandura/ember-legit-forms/commit/6ffb51580ff80ca0522b0459365f47ef345b28b4?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8 for original README entry directly in `ember-legit-forms` repository.

**Comment by jbandura** [comment]
Done in #6
